apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: external-dns
  # namespace: default
spec:
  components:
    - name: external-dns
      type: helm
      properties:
        repoType: "helm"
        url: "https://charts.bitnami.com"
        chart: "external-dns"
        version: "6.17.0"
        values:
          aws: 
            region: "<AWS_REGION>"
            roleArn: "arn:aws:iam::<ACCOUNT_NUMBER>:policy/route53-policy"